# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "dev-tfstate-725876873105"
    key            = "./terraform.tfstate"
    region         = "ap-south-1"
    encrypt        = true
  }
}
