# Base orchestration configuration
# This file prevents individual module execution and enforces run-all usage

locals {
  # Check if running via orchestrated mode (run-all)
  # Set TERRAGRUNT_ORCHESTRATED=true when using run-all commands
  is_orchestrated = tobool(get_env("TERRAGRUNT_ORCHESTRATED", "false"))

  # Allow individual run only if explicitly permitted
  allow_individual = tobool(get_env("TERRAGRUNT_ALLOW_INDIVIDUAL", "false"))

  # Module should run only if orchestrated or individual run is allowed
  should_run = local.is_orchestrated || local.allow_individual
}

# Use generate to create a check script that runs before terraform
generate "orchestration_check" {
  path      = "_orchestration_check.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
# This file is auto-generated by terragrunt
# It ensures modules are run via the orchestrator

variable "_orchestration_mode" {
  type    = bool
  default = ${local.should_run}

  validation {
    condition     = var._orchestration_mode == true
    error_message = <<-EOM

    ══════════════════════════════════════════════════════════════════════
    ⚠️  Individual module execution is disabled!

    Please use the orchestrator script instead:
      cd .. && ./tg <command>

    Available commands:
      ./tg init      - Initialize all modules
      ./tg plan      - Plan all modules
      ./tg apply     - Apply all modules
      ./tg destroy   - Destroy all modules

    To override (not recommended):
      TERRAGRUNT_ALLOW_INDIVIDUAL=true terragrunt <command>
    ══════════════════════════════════════════════════════════════════════
    EOM
  }
}
EOF
}
