# Base orchestration configuration
# This file prevents individual module execution and enforces run-all usage

# Base orchestration configuration

# This file prevents individual module execution and enforces run-all usage

locals {
  # Load global configuration
  global_vars     = yamldecode(file(find_in_parent_folders("global-values.yaml")))
  aws_region      = local.global_vars.global.cloud_storage_region
  environment     = local.global_vars.global.environment
  building_block  = local.global_vars.global.building_block
  target_account  = get_env("TF_VAR_aws_account_id", "")

  # Check if running via orchestrated mode (run-all)
  # Set TERRAGRUNT_ORCHESTRATED=true when using run-all commands
  is_orchestrated = tobool(get_env("TERRAGRUNT_ORCHETRATED", "false"))
 
  # Allow individual run only if explicitly permitted
  allow_individual = tobool(get_env("TERRAGRUNT_ALLOW_INDIVIDUAL", "false"))
 
  # Module should run only if orchestrated or individual run is allowed
  should_run = local.is_orchestrated || local.allow_individual
}
 
# Generate AWS provider with cross-account role assumption
generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "aws" {
  region = "${local.aws_region}"
  assume_role {
    role_arn     = "arn:aws:iam::${local.target_account}:role/cross-account-codebuild-role"
    session_name = "terragrunt-deployment"
  }
  default_tags {
    tags = {
      Environment   = "${local.environment}"
      BuildingBlock = "${local.building_block}"
      ManagedBy     = "Terragrunt"
    }
  }
}
EOF
}
 
# Use generate to create a check script that runs before terraform
generate "orchestration_check" {
  path      = "_orchestration_check.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
# This file is auto-generated by terragrunt
# It ensures modules are run via the orchestrator
 
variable "_orchestration_mode" {
  type    = bool
  default = ${local.should_run}
 
  validation {
    condition     = var._orchestration_mode == true
    error_message = <<-EOM
 
    ══════════════════════════════════════════════════════════════════════
    ⚠️  Individual module execution is disabled!
 
    Please use the orchestrator script instead:
      cd .. && ./tg <command>
 
    Available commands:
      ./tg init      - Initialize all module
      ./tg plan      - Plan all modules
      ./tg apply     - Apply all modules
      ./tg destroy   - Destroy all modules
 
    To override (not recommended):
      TERRAGRUNT_ALLOW_INDIVIDUAL=true terragrunt <command>
    ══════════════════════════════════════════════════════════════════════
    EOM
  }
}
EOF
}
